---
title: "Some Analysis"
author: "Aaron Gullickson"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(here)
source("check_packages.R")
load(here("output","politics.RData"))
```

```{r theme-mine, include=FALSE}
theme_mine <- function() {
  theme_bw()+
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.title = element_text(size=8),
          axis.text = element_text(size=7),
          legend.text=element_text(size=7),
          legend.title=element_text(size=8),
          legend.key.size = unit(0.8,"line"),
          strip.text = element_text(size=7))
}
```

## Introduction

This is just an R Markdown document with a bit of code in it that we will use for test purposes. We will be analyzing the ANES data in the output directory.

```{r gender-ed-graph}
ggplot(subset(politics, president!="No Vote" & gender!="Other"), 
       aes(x=president, y=..prop.., group=educ, fill=educ))+
  geom_bar(position = "dodge")+
  labs(title="Presidential choice by educational level, 2016",
       x=NULL,
       y="percent of education group",
       fill="Education",
       caption="Source: ANES 2016")+
  scale_y_continuous(label=scales::percent)+
  scale_fill_brewer(palette="PuBuGn")+
  facet_wrap(~gender)+
  theme_dark()
```

```{r voting-income-boxplot}
ggplot(politics, aes(x=reorder(president, income, median), y=income*1000))+
  geom_boxplot(fill="grey", outlier.color="red")+
  scale_y_continuous(label=scales::dollar)+
  labs(x=NULL, y="annual household income",
       title="Comparative boxplots of annual household income by vote",
       caption="Source: ANES 2016")+
  theme_dark()
```

```{r voting-income-violin}
ggplot(politics, aes(x=reorder(president, income, median), y=income*1000))+
  geom_violin(fill="grey", outlier.color="red")+
  scale_y_continuous(label=scales::dollar)+
  labs(x=NULL, y="annual household income",
       title="Comparative violin plots of annual household income (in 1000s USD) by vote",
       caption="Source: ANES 2016")+
  theme_dark()
```

```{r models, results='asis'}
model1 <- glm(I(president=="Trump")~gender, 
              data=subset(politics, president=="Trump" | president=="Clinton"))
model2 <- update(model1, .~.+age+race+income+educ)
model3 <- update(model2, .~.+relig)
knitreg(list(model1, model2, model3),
        digits=3, 
        custom.coef.names=c("Intercept","Female","Other","Age","Black",
                            "Latino","Asian/Pacific Islander","American Indian",
                            "Other/Mixed","Income (1000 USD)",
                            "High school diploma",
                            "Some college, less than four year degree",
                            "Bachelors degree","Graduate degree",
                            "Evangelical Protestant","Catholic","Jewish",
                            "Non-religious","Other religion"),
        groups=list("Gender (male ref.)"=2:3,"Race (white ref.)"=5:9,
                    "Highest degree (none ref.)"=11:14,
                    "Religion (mainline protestant ref.)"=15:19),
        caption="Logistic regression models predicting voting for Trump rather than Clinton in 2016",
        caption.above=TRUE)
```
